TESTPROGS += parse/a-info \
	parse/blowe \
	parse/blowm \
	parse/body \
	parse/brand \
	parse/drop \
	parse/e-info \
	parse/f-info \
	parse/flavor \
	parse/graphics \
	parse/h-info \
	parse/house-info \
	parse/k-info \
	parse/lore \
	parse/mbase \
	parse/mspell \
	parse/names \
	parse/objbase \
	parse/objprop \
	parse/p-info \
	parse/pain \
	parse/parse \
	parse/partrap \
	parse/proj \
	parse/pursuit \
	parse/r-info \
	parse/sex-info \
	parse/slay \
	parse/ui_knowledge \
	parse/v-info \
	parse/warning \
	parse/world \
	parse/z-info
