MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

CONFIG = Adurant.txt Aros.txt Ascar.txt Brilthor.txt Brithon.txt Celon.txt \
 DryRiver.txt Duilwen.txt Esgalduin.txt Esgalduin1.txt Esgalduin2.txt Gate.txt \
 Gelion.txt Ginglith.txt Glithui.txt GreaterGelion.txt Lammoth1.txt \
 Lammoth2.txt Legolin.txt Lithir.txt LittleGelion.txt Malduin.txt Mindeb.txt \
 Mithrim1.txt Mithrim2.txt Mithrim3.txt Mithrim4.txt Narog.txt Nenning.txt \
 Ringwil.txt Rivil.txt Sirion.txt Teiglin.txt Thalos.txt
PACKAGE = gamedata/rivers
