/**
 * \file list-smith-types.h
 * \brief List of smithing categories
 */
/* code_name, string_name */
SMITH_TYPE(WEAPON,	ARROW,		"Arrows")
SMITH_TYPE(WEAPON,	BOW,		"Bow")
SMITH_TYPE(WEAPON,	DIGGING,	"Digger")
SMITH_TYPE(WEAPON,	HAFTED,		"Blunt Weapon")
SMITH_TYPE(WEAPON,	POLEARM,	"Axe or Polearm")
SMITH_TYPE(WEAPON,	SWORD,		"Sword")
SMITH_TYPE(ARMOUR,	BOOTS,		"Boots")
SMITH_TYPE(ARMOUR,	GLOVES,		"Gloves")
SMITH_TYPE(ARMOUR,	HELM,		"Helm")
SMITH_TYPE(ARMOUR,	CROWN,		"Crown")
SMITH_TYPE(ARMOUR,	SHIELD,		"Shield")
SMITH_TYPE(ARMOUR,	CLOAK,		"Cloak")
SMITH_TYPE(ARMOUR,	SOFT_ARMOR,	"Soft Armour")
SMITH_TYPE(ARMOUR,	MAIL,		"Mail")
SMITH_TYPE(JEWELRY,	LIGHT,		"Light")
SMITH_TYPE(JEWELRY,	AMULET,		"Amulet")
SMITH_TYPE(JEWELRY,	RING,		"Ring")
SMITH_TYPE(JEWELRY,	HORN,		"Horn")
