/**
 * \file list-mon-race-flags.h
 * \brief monster race flags
 *
 */
/* symbol		type			descr */
RF(NONE,		RFT_NONE,		"")
RF(UNIQUE,		RFT_OBV,		"")
RF(QUESTOR,		RFT_OBV,		"")
RF(MALE,		RFT_OBV,		"")
RF(FEMALE,		RFT_OBV,		"")
RF(NAME_COMMA,	RFT_OBV,		"")
RF(SPECIAL_GEN,	RFT_OBV,		"")
RF(CHAR_CLEAR,	RFT_DISP,		"")
RF(ATTR_MULTI,	RFT_DISP,		"")
RF(ATTR_FLICKER,RFT_DISP,		"")
RF(FORCE_DEPTH,	RFT_GEN,		"")
RF(INVISIBLE,	RFT_NOTE,		"is very difficult to see")
RF(MULTIPLY,	RFT_NOTE,		"breeds explosively")
RF(REGENERATE,	RFT_NOTE,		"regenerates quickly")
RF(NO_CRIT,		RFT_NOTE,		"cannot be critically hit")
RF(RES_CRIT,	RFT_NOTE,		"is resistant to critical hits")
RF(FRIEND,		RFT_GROUP,		"sometimes appears in groups")
RF(FRIENDS,		RFT_GROUP,		"usually appears in groups")
RF(ESCORT,		RFT_GROUP,		"usually appears with escorts")
RF(ESCORTS,		RFT_GROUP,		"usually appears with many escorts")
RF(UNIQUE_FRIEND,RFT_BEHAV,		"")
RF(FLEE,		RFT_BEHAV,		"")
RF(RIDEABLE,	RFT_BEHAV,		"")
RF(NEVER_MOVE,	RFT_BEHAV,		"")
RF(HIDDEN_MOVE,	RFT_BEHAV,		"")
RF(RAND_25,		RFT_BEHAV,		"")
RF(RAND_50,		RFT_BEHAV,		"")
RF(GLOW,		RFT_BEHAV,		"")
RF(TERRITORIAL,	RFT_BEHAV,		"")
RF(SHORT_SIGHTED,RFT_BEHAV,		"")
RF(MINDLESS,	RFT_MIND,		"mindless")
RF(SMART,		RFT_MIND,		"intelligent")
RF(CRUEL_BLOW,	RFT_ABIL,		"cruel blow")
RF(EXCHANGE,	RFT_ABIL,		"exchange places")
RF(RIPOSTE,		RFT_ABIL,		"riposte")
RF(FLANKING,	RFT_ABIL,		"flanking")
RF(CHARGE,		RFT_ABIL,		"charge")
RF(ELFBANE,		RFT_ABIL_OBV,		"elf-bane")
RF(KNOCK_BACK,	RFT_ABIL,		"knock back")
RF(CRIPPLING,	RFT_ABIL,		"crippling shot")
RF(OPPORTUNIST,	RFT_ABIL,		"opportunist")
RF(ZONE,		RFT_ABIL,		"zone of control")
RF(DROP_33,		RFT_DROP,		"")
RF(DROP_100,	RFT_DROP,		"")
RF(DROP_1D2,	RFT_DROP,		"")
RF(DROP_2D2,	RFT_DROP,		"")
RF(DROP_3D2,	RFT_DROP,		"")
RF(DROP_4D2,	RFT_DROP,		"")
RF(DROP_GOOD,	RFT_DROP,		"")
RF(DROP_GREAT,	RFT_DROP,		"")
RF(FLYING,		RFT_MOVE,		"fly")
RF(PASS_DOOR,	RFT_MOVE,		"pass through doors")
RF(UNLOCK_DOOR,	RFT_MOVE,		"unlock doors")
RF(OPEN_DOOR,	RFT_MOVE,		"open doors")
RF(BASH_DOOR,	RFT_MOVE,		"bash down doors")
RF(PASS_WALL,	RFT_MOVE,		"pass through walls")
RF(KILL_WALL,	RFT_MOVE,		"bore through walls")
RF(TUNNEL_WALL,	RFT_MOVE,		"tunnel through walls")
RF(TAKE_ITEM,	RFT_MOVE,		"pick up objects")
RF(KILL_ITEM,	RFT_MOVE,		"destroy objects")
RF(ORC,			RFT_RACE_N,		"orc")
RF(TROLL,		RFT_RACE_N,		"troll")
RF(SERPENT,		RFT_RACE_N,		"serpent")
RF(DRAGON,		RFT_RACE_N,		"dragon")
RF(RAUKO,		RFT_RACE_N,		"rauko")
RF(SPIDER,		RFT_RACE_N,		"spider")
RF(WOLF,		RFT_RACE_N,		"wolf")
RF(ELF,			RFT_RACE_N,		"elf")
RF(DWARF,		RFT_RACE_N,		"dwarf")
RF(HUMAN,		RFT_RACE_N,		"human")
RF(UNDEAD,		RFT_RACE_A,		"undead")
RF(HURT_LIGHT,	RFT_VULN,		"bright light")
RF(STONE,		RFT_VULN,		"shattering")
RF(HURT_FIRE,	RFT_VULN_I,		"fire")
RF(HURT_COLD,	RFT_VULN_I,		"cold")
RF(RES_FIRE,	RFT_RES,		"fire")
RF(RES_COLD,	RFT_RES,		"cold")
RF(RES_POIS,	RFT_RES,		"poison")
RF(NO_FEAR,		RFT_PROT,		"frightened")
RF(NO_STUN,		RFT_PROT,		"stunned")
RF(NO_CONF,		RFT_PROT,		"confused")
RF(NO_SLEEP,	RFT_PROT,		"put to sleep")
RF(NO_SLOW,		RFT_PROT,		"slowed")
/* end flags */
