/**
 * \file list-tvals.h
 * \brief List of object base types
 */
/* code_name, string_name */
TV(NULL, "none")
TV(NOTE, "note")
TV(USELESS, "skeleton")
TV(METAL, "metal")
TV(CHEST, "chest")
TV(ARROW, "arrow")
TV(BOW, "bow")
TV(DIGGING, "digger")
TV(HAFTED, "hafted")
TV(POLEARM, "polearm")
TV(SWORD, "sword")
TV(BOOTS, "boots")
TV(GLOVES, "gloves")
TV(HELM, "helm")
TV(CROWN, "crown")
TV(SHIELD, "shield")
TV(CLOAK, "cloak")
TV(SOFT_ARMOR, "soft armor")
TV(MAIL, "mail")
TV(LIGHT, "light")
TV(AMULET, "amulet")
TV(RING, "ring")
TV(STAFF, "staff")
TV(HORN, "horn")
TV(POTION, "potion")
TV(FLASK, "flask")
TV(FOOD, "food")
TV(HERB, "herb")
TV(EASTER, "easter")
